### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by Novaal** [ionic-team/stencil-redux#12]
Can you please update the [npm package](https://www.npmjs.com/package/@stencil/redux) to a new build of this repo, as i would like to use the 'unsubscribe()' method without needing to link this repo.

This could also be a nightly build or a prerelease version with an alpha/beta/rc-tag.

Thank you!

**Comment by cajusber** [comment]
Yea great idea :)

**Comment by dwieeb** [comment]
0.1.0 is out! 🎉
