### ISSUE TITLE
Using <slot /> ?

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil-redux#13]
As soon as using `<slot />`, the `this.store.setStore()` won't work anymore, because the slots `componentWillLoad()` hook will be executed *before* the parents `componentWillLoad()`, e.g.

    
    <my-component> 
          <my-child-component /> 
    </my-component>

This will throw an error:

    TypeError: Cannot read property 'subscribe' of undefined
    at Object.mapStateToProps

Does anyone have a nice and clean solution for this?
There already is a workaround, but this looks rather hacky to me: https://medium.com/@michakaliszewski/stencil-redux-slot-components-setup-d5efce091842
https://github.com/ionic-team/stencil/issues/1261

**Comment by kraftwer1** [comment]
Found the bug: https://github.com/ionic-team/stencil/issues/1261

It works, as long as the parent component appears *before* the child component in alphabetic order. E.g.:


<my-component>
  <my-component-child /> 
</my-component>


<my-component>
  <my-child-component /> 
</my-component>

**Comment by jarrvis** [comment]
Yes also had problems with that one:
https://medium.com/@michakaliszewski/stencil-redux-slot-components-setup-d5efce091842
Alphabetic order sounds funny but this is exactly what I found out. I prepared a repo to reproduce it (on Chrome definitely tested):
https://github.com/jarrvis/stencil-component-lifecycle-test
@kraftwer1 You hotfix it in your app with
```
  document.querySelector("my-root-component").componentOnReady().then(() => {
         ...
      });
```
async/await:
```
async componentWillLoad() {
    await document.querySelector("my-root-component").componentOnReady()
}
```
 is not working fine for some reason when my-root-component was actually loaded before child (correct order). Did not analyze why yet

**Comment by luciomartinez** [comment]
Hope this helps: https://github.com/ionic-team/stencil-redux/pull/45
