### ISSUE TITLE
mapDispatchToProps is wrong

### ISSUE THREAD

**Issue by nripendra** [ionic-team/stencil-redux#2]
The implementation of mapDispatchToProps seems to be wrong.

I think this is more appropriate implementation.

```ts
function mapDispatchToProps(component: any, props: any) {
    Object.keys(props).forEach(actionName => {
      const action = props[actionName];
      Object.defineProperty(component, actionName, {
        get: () => (...args: any[]) => _store.dispatch(action(...args)),
        configurable: true,
        enumerable: true
      })
    });
  }
```

**Comment by mlynch** [comment]
Wrong in what way?

**Comment by tonai** [comment]
Maybe because original redux actions simply return objects: 
```js
function myAction() {
  return { type: 'MY_ACTION' };
}
```
redux-thunk should be an optional package.

In the `mapDispatchToProps` implementation that @nripendra is pointing, it seems that you are waiting for actions that look more like this:
```js
function myAction() {
  return dispatch => dispatch({ type: 'MY_ACTION' });
}
```

**Comment by mlynch** [comment]
Ah, good point on thunk, I tend to always include it so over looked this. Thoughts on making thunk required? Makes it so much easier to build actions

**Comment by tonai** [comment]
Yes it is a very handy package.
And you should not care whether the action return an object or a function.
It is handled by the middleware.

In my opinion it would be great to have the `mapDispatchToProps` declaration in the component being more react-redux-like.

In fact, `react-redux` does have a shorthand where you only write something like this (like what you have to write with this package):
```js
import { updateUserInput } from 'myActions.js';
const mapDispatchToProps = {
  updateUserInput
};
```

But the classic way is more like this:
```js
import { updateUserInput } from 'myActions.js';
const mapDispatchToProps = (dispatch) => ({
  updateUserInput: value => dispatch(updateUserInput(value))
});
```

And letting the user manage the way he like dispatching actions, like, for example, using the `bindActionCreators` helper from `redux` to write this:
```js
import { updateUserInput } from 'myActions.js';
const mapDispatchToProps = (dispatch) => bindActionCreators({updateUserInput}, dispatch);
```

**Comment by mlynch** [comment]
Also I'm realizing that `mapStateToProps` is not actually mapping the state to _props_, it's requiring those be `State()` fields. So that needs to be fixed as well

**Comment by pablolazaro** [comment]
Any updates on this?
