### ISSUE TITLE
declare typesafe `Action` 

### ISSUE THREAD

**Issue by nripendra** [ionic-team/stencil-redux#3]
suggestion:

```
export declare type Action<T, TOut> = (...args: T[]) => TOut;
```
Allows for specifying input parameter types and return type.
e.g:
```
registerAccount: Action<IAccount, IReduxAction>;
updateValidationStatus: Action<IAccount | string[], IReduxAction>;
```
if and when implemented Microsoft/TypeScript#5453 will make things even better in future.

**Comment by dwieeb** [comment]
Just pushed a commit that adds a lot more type safety to `@stencil/redux`. 

See usage: https://github.com/ionic-team/stencil-redux#stencil-redux

Should have a release out soon. Thanks!
