### ISSUE TITLE
Latest build fails with @stencil/core 1.8.0

### ISSUE THREAD

**Issue by stanley85** [ionic-team/stencil-redux#69]
This is the counterpart issue to https://github.com/ionic-team/stencil/issues/2015 

I'm submitting a:
[X] bug report

Current behavior:
Updating @stencil/core from 1.7.5 to 1.8.0 breaks compile for stencil-redux

Expected behavior:
Please add some ionic love to stencil-redux and up the core - its 0.18

Steps to reproduce:
Add stencil-redux to a new @stencil/core ^1.8.0 project

Other information:
TypeScript
Import declaration conflicts with local declaration of 'Action'.

./node_modules@stencil\redux\dist\types\global\interfaces.d.ts

import { Action, AnyAction, Store as ReduxStore, Unsubscribe } from 'redux';
export interface Store<S = any, A extends Action = AnyAction> {

**Comment by jthoms1** [comment]
This was resolved in release of 0.1.2
